### ISSUE TITLE
京东保价报错，jsdom依赖也已安装，暂不知问题出在哪，等高人指点

### ISSUE THREAD

**Issue by Rosylusi** [shufflewzc/fakergone#129]
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'jsdom'
Require stack:
- /ql/scripts/shufflewzc_faker2_jd_price.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jd_price.js:25:28)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jd_price.js' ]
}

## 执行结束... 2021-10-09 12:56:54 耗时 0 秒

**Comment by Aaron-lv** [comment]
@895450603 未安装依赖

**Comment by Rosylusi** [comment]
> @895450603 未安装依赖

![image](https://user-images.githubusercontent.com/43165837/136645093-e2eb2718-2257-43dc-a78b-26dee4d25c65.png)
所以这就是我纳闷的地方，我也按照说明安装了依赖

**Comment by windfgg** [comment]
@895450603 npm view jsdom version

**Comment by windfgg** [comment]
@895450603 npm install jsdom -s

**Comment by Aaron-lv** [comment]
@895450603 引号内替换为 pnpm install jsdom -g

**Comment by Rosylusi** [comment]
> pnpm install jsdom -g

成了成了，谢谢

**Comment by 895450603** [comment]
> @895450603 引号内替换为 pnpm install jsdom -g

是不是所有命令都得改成-g重新去运行一遍？
