### ISSUE TITLE
东东玩家互助报错

### ISSUE THREAD

**Issue by lustime** [shufflewzc/fakergone#146]
开始获取互助码.......

❗️东东玩家互助, 错误!
TypeError: Cannot read property 'bizMsg' of undefined
    at /ql/scripts/shufflewzc_faker2_jd_zy_ddwj_help.js:267:26
    at got.post.then.message (/ql/scripts/shufflewzc_faker2_jd_zy_ddwj_help.js:642:6)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by hyzaw** [comment]
东东玩家已结束
