### ISSUE TITLE
Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by creazy412** [shufflewzc/fakergone#150]
第8步增加 |ts 任务日志输出时间戳...
第9步执行proc_file.sh脚本任务...
处理jd_crazy_joy_coin任务。。。
已配置不启用jd_crazy_joy_coin任务，仅杀掉
第10步加载最新的定时任务文件...
第11步将仓库的docker_entrypoint.sh脚本更新至系统/usr/local/bin/docker_entrypoint.sh内...
发送通知
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /scripts/ql.js
- /scripts/sendNotify.js
- /scripts/docker/notify_docker_user.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/scripts/ql.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/scripts/ql.js',
    '/scripts/sendNotify.js',
    '/scripts/docker/notify_docker_user.js'
  ]
}
设定远程仓库地址...
HEAD is now at 89c12e8 update
git pull拉取最新代码...
Already up to date.
Current branch main is up to date.
npm install 安装最新依赖

**Comment by hyzaw** [comment]
pnpm install xxx
