### ISSUE TITLE
京东多合一签到失败

### ISSUE THREAD

**Issue by pythonTaotao** [shufflewzc/fakergone#21]
脚本运行异常，出现报错

**Comment by yyzhou94** [comment]
安装依赖

yum install wget unzip -y

cd QL/scripts

wget https://ghproxy.com/https://github.com/shufflewzc/faker2/releases/download/0.0.1/utils.zip && unzip utils.zip

**Comment by Rosylusi** [comment]
> 安装依赖
> 
> yum install wget unzip -y
> 
> cd QL/scripts
> 
> wget https://ghproxy.com/https://github.com/shufflewzc/faker2/releases/download/0.0.1/utils.zip && unzip utils.zip


这咋整？？
开始执行 京东多合一签到 签到，请稍等...

/root/jd/scripts/utils/JDSignValidator.js:208
    f = {
      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/jd/scripts/utils/JD_DailyBonus.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
京东签到脚本执行异常:Error: Command failed: /usr/bin/node ./utils/JD_DailyBonus.js >> ./result.txt
/root/jd/scripts/utils/JDSignValidator.js:208
    f = {
      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/jd/scripts/utils/JD_DailyBonus.js:35:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by shufflewzc** [comment]
我这边测了没事，你再试试

**Comment by Rosylusi** [comment]
大佬，我是用的是A1不是青龙，试了很多遍了，一开始是提示文件不存在，安装utils.zip之后就提示这个错误

**Comment by coppea** [comment]
我也是这样

**Comment by shufflewzc** [comment]
安装依赖就可以了
