### ISSUE TITLE
京喜牧场报错

### ISSUE THREAD

**Issue by zhq1** [shufflewzc/fakergone#259]
Faker 友情提示：您的脚本正常运行中
京喜牧场
更新时间：2021-11-7
活动入口：京喜APP-我的-京喜牧场
温馨提示：请先手动完成【新手指导任务】再运行脚本

*****开始【京东账号1】*****

打印新手流程进度：当前进度：f-2，下一流程：pause
开始初始化

❗️京喜牧场, 错误!
TypeError: Cannot read properties of undefined (reading 'maintaskId')
    at pasture (/ql/scripts/shufflewzc_faker2/jd_jxmc.js:175:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/shufflewzc_faker2/jd_jxmc.js:110:5

**Comment by zhq1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhq1** [comment]
5G超级盲盒这个应该也失效了
jd_mohe.js

活动时间：2021-8-2到2021-10-29
更新时间：2021-8-8 19:00

**Comment by zhq1** [comment]
搞定了
