### ISSUE TITLE
jd_joy_reward运行报错啊

### ISSUE THREAD

**Issue by w900316** [shufflewzc/fakergone#31]
🔔宠汪汪积分兑换奖品, 开始!
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './utils/JDJRValidator_Pure'
Require stack:
- /ql/scripts/jd_joy_reward1.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/jd_joy_reward1.js:26:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/jd_joy_reward.js' ]
}

**Comment by shufflewzc** [comment]
进群看解决办法
