### ISSUE TITLE
JDJRValidator_Pure.js 会被utils目录下的同名文件覆盖

### ISSUE THREAD

**Issue by WindStill** [shufflewzc/fakergone#58]
拉取repo时，一级目录下的JDJRValidator_Pure.js 会被utils目录下的同名文件覆盖，导致依赖文件找不到。

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../USER_AGENTS.js'
Require stack:
- /ql/scripts/JDJRValidator_Pure.js
- /ql/scripts/shufflewzc_faker2_jd_sign_graphics.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/JDJRValidator_Pure.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/JDJRValidator_Pure.js',
    '/ql/scripts/shufflewzc_faker2_jd_sign_graphics.js'
  ]
}
```

**Comment by WindStill** [comment]
`/ql/scripts/shufflewzc_faker2_jd_sign_graphics.js` 依赖的是同级目录下的 `/ql/scripts/JDJRValidator_Pure.js`
`/ql/scripts/JDJRValidator_Pure.js` 依赖的是同级目录下的 `USER_AGENTS.js`，即代码中的
```
const UA = require('./USER_AGENTS.js').USER_AGENT;
```
但是`/ql/scripts`目录中的`JDJRValidator_Pure.js`会被`/ql/scripts/utils`中的`JDJRValidator_Pure.js`覆盖。
而`/ql/scripts/utils`中的`JDJRValidator_Pure.js`依赖的是上级目录下的`USER_AGENTS.js`，即代码中的
```
const UA = require('../USER_AGENTS.js').USER_AGENT;
```
所以就导致了报错。


```
ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git 
"jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate"
```
这个repo拉取命令应该怎么改？我试了下把依赖中的`utils`和`JDJRValidator_Pure`去了就不会被`utils`中的覆盖了，只去掉其中一个也不行。

但这样的话，一级目录(scripts目录)下的`JDJRValidator_Pure.js`和`utils`是不是就不会更新了？

**Comment by shufflewzc** [comment]
请升级到青龙2.8噢

**Comment by WindStill** [comment]
> 请升级到青龙2.8噢

听说青龙2.8多多少少有点问题，就一直没有升级。

2.2有没有解决方法？

**Comment by shufflewzc** [comment]
> > 请升级到青龙2.8噢
> 
> 听说青龙2.8多多少少有点问题，就一直没有升级。
> 
> 2.2有没有解决方法？

可以手动更改下文件目录

**Comment by WindStill** [comment]
> > > 请升级到青龙2.8噢
> > 
> > 
> > 听说青龙2.8多多少少有点问题，就一直没有升级。
> > 2.2有没有解决方法？
> 
> 可以手动更改下文件目录

不折腾了，直接升到2.8了 😂
