### ISSUE TITLE
签到出问题了

### ISSUE THREAD

**Issue by shanhai2333** [shufflewzc/fakergone#61]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /root/jd/scripts/utils/JDJRValidator_Pure.js
- /root/jd/scripts/utils/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/jd/scripts/utils/JDJRValidator_Pure.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/jd/scripts/utils/JDJRValidator_Pure.js',
    '/root/jd/scripts/utils/JD_DailyBonus.js'
  ]
}
京东签到脚本执行异常:Error: Command failed: /usr/local/bin/node ./utils/JD_DailyBonus.js >> ./result.txt
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /root/jd/scripts/utils/JDJRValidator_Pure.js
- /root/jd/scripts/utils/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/jd/scripts/utils/JDJRValidator_Pure.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/jd/scripts/utils/JDJRValidator_Pure.js',
    '/root/jd/scripts/utils/JD_DailyBonus.js'
  ]
}

**Comment by shufflewzc** [comment]
安装png-js依赖
