### ISSUE TITLE
宠汪汪积分兑换奖品 脚本错误

### ISSUE THREAD

**Issue by shyg866** [shufflewzc/fakergone#69]
TypeError: data[giftSaleInfos] is not iterable
    at joyReward (/ql/scripts/shufflewzc_faker2_jd_joy_reward.js:145:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /ql/scripts/shufflewzc_faker2_jd_joy_reward.js:85:7

**Comment by shyg866** [comment]
可以使用了
