### ISSUE TITLE
Checkck报错

### ISSUE THREAD

**Issue by Rosylusi** [shufflewzc/fakergone#76]
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './ql'
Require stack:
- /ql/scripts/shufflewzc_faker2_jd_CheckCK.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jd_CheckCK.js:8:38)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jd_CheckCK.js' ]
}

## 执行结束... 2021-09-02 12:00:51 耗时 0 秒

**Comment by LuzMasonj** [comment]
同 缺ql

**Comment by lafVinson** [comment]
我也是 一样

**Comment by Anjiu464** [comment]
metoo

**Comment by 123456been** [comment]
同样

**Comment by shufflewzc** [comment]
注意修改拉库命令 以tg群为准

**Comment by didiaochenmonan** [comment]
缺少ql.js这个文件

**Comment by Rosylusi** [comment]
> 注意修改拉库命令 以tg群为准

大佬，TG群进不去啊

**Comment by gold2wave** [comment]
同这个问题，不知道怎么解决

**Comment by shufflewzc** [comment]
已更新
