### ISSUE TITLE
京豆变动TG通知失败，其他脚本正常，找不到原因。

### ISSUE THREAD

**Issue by gnowmil** [shufflewzc/fakergone#80]
jd_bean_change_new.js跟jd_bean_change.js都发送不了通知，jd_all_bean_change.js倒是可以。不解
日志提示如下：
telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1630683224061,
    socket: 1630683224071,
    lookup: 1630683224092,
    connect: 1630683224094,
    secureConnect: 1630683225840,
    upload: 1630683225840,
    response: 1630683226402,
    end: 1630683226403,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 10,
      dns: 21,
      tcp: 2,
      tls: 1746,
      request: 0,
      firstByte: 562,
      download: 1,
      total: 2342
    }
  }
}

========================================================================
有些时候是下面的提示：
telegram发送通知消息失败！！

RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/ql/scripts/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET',
  timings: {
    start: 1630681811017,
    socket: 1630681811022,
    lookup: 1630681811023,
    connect: 1630681811025,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1630681812997,
    abort: undefined,
    phases: {
      wait: 5,
      dns: 1,
      tcp: 2,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 1980
    }
  }
}

**Comment by shufflewzc** [comment]
这几天修复
