### ISSUE TITLE
宠汪汪等报错

### ISSUE THREAD

**Issue by creboy** [shufflewzc/fakergone#88]
## 更新任务状态成功

🔔宠汪汪, 开始!
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './utils/JDJRValidator_Pure'
Require stack:
- /ql/scripts/shufflewzc_faker2_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jd_joy.js:28:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jd_joy.js' ]
}
## 执行结束... 2021-09-08 12:19:11  耗时 0 秒

**Comment by wangjing71** [comment]
修复下依赖库
https://www.notion.so/QL-pannel-Dependent-Librai-164400378c7f4a4587f976e89aea1584

**Comment by creboy** [comment]
这怎么办
F:\QL>docker exec -it QL bash -c "npm install jsdom"
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"17.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm ERR! node_modules/react-codemirror2
npm ERR!   dev react-codemirror2@"^7.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-08T03_57_37_485Z-debug.log
