### ISSUE TITLE
internal/modules/cjs/ ^  Error: Cannot find module './function/common' Require stack: - /ql/scripts/shufflewzc_faker2_jd_aid_factory.js

### ISSUE THREAD

**Issue by YvoIovY** [shufflewzc/fakergone#95]
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './function/common'
Require stack:
- /ql/scripts/shufflewzc_faker2_jd_aid_factory.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jd_aid_factory.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jd_aid_factory.js' ]
}

**Comment by YvoIovY** [comment]
哪位大佬知道如何解决？

**Comment by YvoIovY** [comment]
已解决，拉库命令后面备注少几个，少拉部分文件。
